# This is a basic workflow to help you get started with Actions

name: Sprotna Integracija

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover -s . -p "tests.py"
        continue-on-error: true  # Allow the workflow to continue even if tests fail

      - name: Upload test results
        if: always()  # Ensure this step runs regardless of previous step success
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results.xml

  static-analysis:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run static analysis
        run: pylint main.py > pylint-report.txt
        continue-on-error: true  # Allow the workflow to continue even if tests fail

      - name: Upload static analysis results
        if: always()  # Ensure this step runs regardless of previous step success
        uses: actions/upload-artifact@v2
        with:
          name: pylint-report
          path: pylint-report.txt
